import { NextRequest, NextResponse } from 'next/server';

const MOCK_SONGS = [
  {
    id: 'song-1',
    title: 'Midnight Dreams',
    artist: 'Luna Echo',
    album: 'Night Tales',
    duration: 240,
    imageUrl: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 'song-2',
    title: 'Electric Horizon',
    artist: 'Neon Pulse',
    album: 'Synthetic Waves',
    duration: 198,
    imageUrl: 'https://picsum.photos/300/300?random=2',
  },
  {
    id: 'song-3',
    title: 'Celestial Journey',
    artist: 'Star Gaze',
    album: 'Cosmic Explorations',
    duration: 275,
    imageUrl: 'https://picsum.photos/300/300?random=3',
  },
  {
    id: 'song-4',
    title: 'Urban Symphony',
    artist: 'City Sounds',
    album: 'Metropolitan',
    duration: 210,
    imageUrl: 'https://picsum.photos/300/300?random=4',
  },
  {
    id: 'song-5',
    title: 'Ocean Waves',
    artist: 'Coastal Harmony',
    album: 'Seaside Dreams',
    duration: 265,
    imageUrl: 'https://picsum.photos/300/300?random=5',
  },
  {
    id: 'song-6',
    title: 'Forest Whispers',
    artist: 'Nature Sounds',
    album: 'Earthly Melodies',
    duration: 220,
    imageUrl: 'https://picsum.photos/300/300?random=6',
  },
  {
    id: 'song-7',
    title: 'Desert Fire',
    artist: 'Sand Storm',
    album: 'Arid Beats',
    duration: 185,
    imageUrl: 'https://picsum.photos/300/300?random=7',
  },
  {
    id: 'song-8',
    title: 'Mountain Peak',
    artist: 'Alpine Echo',
    album: 'High Altitudes',
    duration: 245,
    imageUrl: 'https://picsum.photos/300/300?random=8',
  },
  {
    id: 'song-9',
    title: 'Neon Lights',
    artist: 'Synthetic Dreams',
    album: 'Digital Age',
    duration: 215,
    imageUrl: 'https://picsum.photos/300/300?random=9',
  },
  {
    id: 'song-10',
    title: 'Velvet Rain',
    artist: 'Smooth Jazz Co',
    album: 'Evening Sessions',
    duration: 268,
    imageUrl: 'https://picsum.photos/300/300?random=10',
  },
  {
    id: 'song-11',
    title: 'Crystal Clear',
    artist: 'Pure Sound',
    album: 'Clarity',
    duration: 192,
    imageUrl: 'https://picsum.photos/300/300?random=11',
  },
  {
    id: 'song-12',
    title: 'Sunset Boulevard',
    artist: 'Golden Hour',
    album: 'West Coast',
    duration: 242,
    imageUrl: 'https://picsum.photos/300/300?random=12',
  },
  {
    id: 'song-13',
    title: 'Rhythmic Pulse',
    artist: 'Beat Masters',
    album: 'Groove Lab',
    duration: 206,
    imageUrl: 'https://picsum.photos/300/300?random=13',
  },
  {
    id: 'song-14',
    title: 'Aurora Borealis',
    artist: 'Northern Lights',
    album: 'Arctic Dreams',
    duration: 289,
    imageUrl: 'https://picsum.photos/300/300?random=14',
  },
  {
    id: 'song-15',
    title: 'Echoes in Time',
    artist: 'Temporal Echo',
    album: 'Timeless',
    duration: 251,
    imageUrl: 'https://picsum.photos/300/300?random=15',
  },
  {
    id: 'song-16',
    title: 'Digital Dreams',
    artist: 'Cyber Wave',
    album: 'Matrix Sounds',
    duration: 218,
    imageUrl: 'https://picsum.photos/300/300?random=16',
  },
  {
    id: 'song-17',
    title: 'Heartbeat',
    artist: 'Pulse',
    album: 'Living',
    duration: 203,
    imageUrl: 'https://picsum.photos/300/300?random=17',
  },
  {
    id: 'song-18',
    title: 'Infinity Loop',
    artist: 'Endless Motion',
    album: 'Forever',
    duration: 257,
    imageUrl: 'https://picsum.photos/300/300?random=18',
  },
  {
    id: 'song-19',
    title: 'Quantum Leap',
    artist: 'Physics Band',
    album: 'Dimensions',
    duration: 235,
    imageUrl: 'https://picsum.photos/300/300?random=19',
  },
  {
    id: 'song-20',
    title: 'Stellar Night',
    artist: 'Cosmic Rays',
    album: 'Space Odyssey',
    duration: 278,
    imageUrl: 'https://picsum.photos/300/300?random=20',
  },
  {
    id: 'song-21',
    title: 'Thunder Road',
    artist: 'Storm Chase',
    album: 'Weather Patterns',
    duration: 241,
    imageUrl: 'https://picsum.photos/300/300?random=21',
  },
  {
    id: 'song-22',
    title: 'Violet Skies',
    artist: 'Purple Haze',
    album: 'Color Theory',
    duration: 226,
    imageUrl: 'https://picsum.photos/300/300?random=22',
  },
  {
    id: 'song-23',
    title: 'Emerald Garden',
    artist: 'Green Peace',
    album: 'Nature Calls',
    duration: 249,
    imageUrl: 'https://picsum.photos/300/300?random=23',
  },
  {
    id: 'song-24',
    title: 'Silver Lining',
    artist: 'Metallic Sound',
    album: 'Reflections',
    duration: 214,
    imageUrl: 'https://picsum.photos/300/300?random=24',
  },
  {
    id: 'song-25',
    title: 'Golden Ratio',
    artist: 'Math Rock',
    album: 'Precision',
    duration: 267,
    imageUrl: 'https://picsum.photos/300/300?random=25',
  },
  {
    id: 'song-26',
    title: 'Midnight Oil',
    artist: 'Late Night Crew',
    album: 'Nocturne',
    duration: 233,
    imageUrl: 'https://picsum.photos/300/300?random=26',
  },
  {
    id: 'song-27',
    title: 'Diamond Dust',
    artist: 'Precious Gems',
    album: 'Sparkle',
    duration: 247,
    imageUrl: 'https://picsum.photos/300/300?random=27',
  },
  {
    id: 'song-28',
    title: 'Phoenix Rising',
    artist: 'Rebirth Band',
    album: 'New Beginnings',
    duration: 271,
    imageUrl: 'https://picsum.photos/300/300?random=28',
  },
  {
    id: 'song-29',
    title: 'Silent Night',
    artist: 'Quiet Moments',
    album: 'Peaceful',
    duration: 188,
    imageUrl: 'https://picsum.photos/300/300?random=29',
  },
  {
    id: 'song-30',
    title: 'Cosmic Dance',
    artist: 'Space Walkers',
    album: 'Zero Gravity',
    duration: 264,
    imageUrl: 'https://picsum.photos/300/300?random=30',
  },
  {
    id: 'song-31',
    title: 'Waterfall Rush',
    artist: 'River Flow',
    album: 'Liquid Motion',
    duration: 229,
    imageUrl: 'https://picsum.photos/300/300?random=31',
  },
  {
    id: 'song-32',
    title: 'Fire and Ice',
    artist: 'Temperature Rising',
    album: 'Extremes',
    duration: 252,
    imageUrl: 'https://picsum.photos/300/300?random=32',
  },
  {
    id: 'song-33',
    title: 'Gravity Well',
    artist: 'Heavy Bass',
    album: 'Deep Space',
    duration: 276,
    imageUrl: 'https://picsum.photos/300/300?random=33',
  },
  {
    id: 'song-34',
    title: 'Wind Chimes',
    artist: 'Breeze Makers',
    album: 'Air',
    duration: 197,
    imageUrl: 'https://picsum.photos/300/300?random=34',
  },
  {
    id: 'song-35',
    title: 'Shadow Play',
    artist: 'Dark Ambient',
    album: 'Shadows',
    duration: 238,
    imageUrl: 'https://picsum.photos/300/300?random=35',
  },
  {
    id: 'song-36',
    title: 'Sunburst',
    artist: 'Solar Flare',
    album: 'Brightness',
    duration: 220,
    imageUrl: 'https://picsum.photos/300/300?random=36',
  },
  {
    id: 'song-37',
    title: 'Mystic Portal',
    artist: 'Enigma Machine',
    album: 'Hidden Worlds',
    duration: 283,
    imageUrl: 'https://picsum.photos/300/300?random=37',
  },
  {
    id: 'song-38',
    title: 'Orbital Motion',
    artist: 'Planet Groove',
    album: 'Planetary',
    duration: 255,
    imageUrl: 'https://picsum.photos/300/300?random=38',
  },
  {
    id: 'song-39',
    title: 'Aurora Wake',
    artist: 'Dawn Chorus',
    album: 'Morning Light',
    duration: 211,
    imageUrl: 'https://picsum.photos/300/300?random=39',
  },
  {
    id: 'song-40',
    title: 'Infinite Loop',
    artist: 'Code Runner',
    album: 'Software',
    duration: 243,
    imageUrl: 'https://picsum.photos/300/300?random=40',
  },
  {
    id: 'song-41',
    title: 'Velvet Blue',
    artist: 'Deep Color',
    album: 'Hues',
    duration: 265,
    imageUrl: 'https://picsum.photos/300/300?random=41',
  },
  {
    id: 'song-42',
    title: 'Sonic Boom',
    artist: 'Thunderous Sound',
    album: 'Explosions',
    duration: 208,
    imageUrl: 'https://picsum.photos/300/300?random=42',
  },
  {
    id: 'song-43',
    title: 'Twilight Zone',
    artist: 'Between Times',
    album: 'Liminal',
    duration: 237,
    imageUrl: 'https://picsum.photos/300/300?random=43',
  },
  {
    id: 'song-44',
    title: 'Cascade Falls',
    artist: 'Water Bearer',
    album: 'Flow',
    duration: 270,
    imageUrl: 'https://picsum.photos/300/300?random=44',
  },
  {
    id: 'song-45',
    title: 'Prism Light',
    artist: 'Spectrum',
    album: 'Rainbow',
    duration: 221,
    imageUrl: 'https://picsum.photos/300/300?random=45',
  },
  {
    id: 'song-46',
    title: 'Frost Bite',
    artist: 'Ice Breakers',
    album: 'Cold',
    duration: 246,
    imageUrl: 'https://picsum.photos/300/300?random=46',
  },
  {
    id: 'song-47',
    title: 'Thunder Drums',
    artist: 'Percussion Kings',
    album: 'Rhythm Nation',
    duration: 234,
    imageUrl: 'https://picsum.photos/300/300?random=47',
  },
  {
    id: 'song-48',
    title: 'Moonlight Serenade',
    artist: 'Night Owl',
    album: 'Nocturnal',
    duration: 259,
    imageUrl: 'https://picsum.photos/300/300?random=48',
  },
  {
    id: 'song-49',
    title: 'Eternal Flame',
    artist: 'Forever Burning',
    album: 'Immortal',
    duration: 272,
    imageUrl: 'https://picsum.photos/300/300?random=49',
  },
  {
    id: 'song-50',
    title: 'Void Echo',
    artist: 'Silent Void',
    album: 'Empty Space',
    duration: 199,
    imageUrl: 'https://picsum.photos/300/300?random=50',
  },
  {
    id: 'song-51',
    title: 'Harmony Line',
    artist: 'Perfect Chord',
    album: 'Melodic',
    duration: 228,
    imageUrl: 'https://picsum.photos/300/300?random=51',
  },
  {
    id: 'song-52',
    title: 'Velocity Rise',
    artist: 'Speed Demon',
    album: 'Fast Track',
    duration: 181,
    imageUrl: 'https://picsum.photos/300/300?random=52',
  },
];

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get('q');

  if (!query) {
    return NextResponse.json(MOCK_SONGS);
  }

  const lowerQuery = query.toLowerCase();
  const filtered = MOCK_SONGS.filter(
    (song) =>
      song.title.toLowerCase().includes(lowerQuery) ||
      song.artist.toLowerCase().includes(lowerQuery) ||
      song.album.toLowerCase().includes(lowerQuery)
  );

  return NextResponse.json(filtered);
}
