import { NextRequest, NextResponse } from 'next/server';

const MOCK_SONGS = [
  {
    id: 'song-1',
    title: 'Midnight Dreams',
    artist: 'Luna Echo',
    album: 'Night Tales',
    duration: 240,
    imageUrl: 'https://picsum.photos/300/300?random=1',
  },
  {
    id: 'song-2',
    title: 'Electric Horizon',
    artist: 'Neon Pulse',
    album: 'Synthetic Waves',
    duration: 198,
    imageUrl: 'https://picsum.photos/300/300?random=2',
  },
  {
    id: 'song-3',
    title: 'Celestial Journey',
    artist: 'Star Gaze',
    album: 'Cosmic Explorations',
    duration: 275,
    imageUrl: 'https://picsum.photos/300/300?random=3',
  },
  {
    id: 'song-4',
    title: 'Urban Symphony',
    artist: 'City Sounds',
    album: 'Metropolitan',
    duration: 210,
    imageUrl: 'https://picsum.photos/300/300?random=4',
  },
  {
    id: 'song-5',
    title: 'Ocean Waves',
    artist: 'Coastal Harmony',
    album: 'Seaside Dreams',
    duration: 265,
    imageUrl: 'https://picsum.photos/300/300?random=5',
  },
  {
    id: 'song-6',
    title: 'Forest Whispers',
    artist: 'Nature Sounds',
    album: 'Earthly Melodies',
    duration: 220,
    imageUrl: 'https://picsum.photos/300/300?random=6',
  },
  {
    id: 'song-7',
    title: 'Desert Fire',
    artist: 'Sand Storm',
    album: 'Arid Beats',
    duration: 185,
    imageUrl: 'https://picsum.photos/300/300?random=7',
  },
  {
    id: 'song-8',
    title: 'Mountain Peak',
    artist: 'Alpine Echo',
    album: 'High Altitudes',
    duration: 245,
    imageUrl: 'https://picsum.photos/300/300?random=8',
  },
  {
    id: 'song-9',
    title: 'Neon Lights',
    artist: 'Synthetic Dreams',
    album: 'Digital Age',
    duration: 215,
    imageUrl: 'https://picsum.photos/300/300?random=9',
  },
  {
    id: 'song-10',
    title: 'Velvet Rain',
    artist: 'Smooth Jazz Co',
    album: 'Evening Sessions',
    duration: 268,
    imageUrl: 'https://picsum.photos/300/300?random=10',
  },
  {
    id: 'song-11',
    title: 'Crystal Clear',
    artist: 'Pure Sound',
    album: 'Clarity',
    duration: 192,
    imageUrl: 'https://picsum.photos/300/300?random=11',
  },
  {
    id: 'song-12',
    title: 'Sunset Boulevard',
    artist: 'Golden Hour',
    album: 'West Coast',
    duration: 242,
    imageUrl: 'https://picsum.photos/300/300?random=12',
  },
  {
    id: 'song-13',
    title: 'Rhythmic Pulse',
    artist: 'Beat Masters',
    album: 'Groove Lab',
    duration: 206,
    imageUrl: 'https://picsum.photos/300/300?random=13',
  },
  {
    id: 'song-14',
    title: 'Aurora Borealis',
    artist: 'Northern Lights',
    album: 'Arctic Dreams',
    duration: 289,
    imageUrl: 'https://picsum.photos/300/300?random=14',
  },
  {
    id: 'song-15',
    title: 'Echoes in Time',
    artist: 'Temporal Echo',
    album: 'Timeless',
    duration: 251,
    imageUrl: 'https://picsum.photos/300/300?random=15',
  },
  {
    id: 'song-16',
    title: 'Digital Dreams',
    artist: 'Cyber Wave',
    album: 'Matrix Sounds',
    duration: 218,
    imageUrl: 'https://picsum.photos/300/300?random=16',
  },
  {
    id: 'song-17',
    title: 'Heartbeat',
    artist: 'Pulse',
    album: 'Living',
    duration: 203,
    imageUrl: 'https://picsum.photos/300/300?random=17',
  },
  {
    id: 'song-18',
    title: 'Infinity Loop',
    artist: 'Endless Motion',
    album: 'Forever',
    duration: 257,
    imageUrl: 'https://picsum.photos/300/300?random=18',
  },
  {
    id: 'song-19',
    title: 'Quantum Leap',
    artist: 'Physics Band',
    album: 'Dimensions',
    duration: 235,
    imageUrl: 'https://picsum.photos/300/300?random=19',
  },
  {
    id: 'song-20',
    title: 'Stellar Night',
    artist: 'Cosmic Rays',
    album: 'Space Odyssey',
    duration: 278,
    imageUrl: 'https://picsum.photos/300/300?random=20',
  },
  {
    id: 'song-21',
    title: 'Thunder Road',
    artist: 'Storm Chase',
    album: 'Weather Patterns',
    duration: 241,
    imageUrl: 'https://picsum.photos/300/300?random=21',
  },
  {
    id: 'song-22',
    title: 'Violet Skies',
    artist: 'Purple Haze',
    album: 'Color Theory',
    duration: 226,
    imageUrl: 'https://picsum.photos/300/300?random=22',
  },
  {
    id: 'song-23',
    title: 'Emerald Garden',
    artist: 'Green Peace',
    album: 'Nature Calls',
    duration: 249,
    imageUrl: 'https://picsum.photos/300/300?random=23',
  },
  {
    id: 'song-24',
    title: 'Silver Lining',
    artist: 'Metallic Sound',
    album: 'Reflections',
    duration: 214,
    imageUrl: 'https://picsum.photos/300/300?random=24',
  },
  {
    id: 'song-25',
    title: 'Golden Ratio',
    artist: 'Math Rock',
    album: 'Precision',
    duration: 267,
    imageUrl: 'https://picsum.photos/300/300?random=25',
  },
  {
    id: 'song-26',
    title: 'Midnight Oil',
    artist: 'Late Night Crew',
    album: 'Nocturne',
    duration: 233,
    imageUrl: 'https://picsum.photos/300/300?random=26',
  },
  {
    id: 'song-27',
    title: 'Diamond Dust',
    artist: 'Precious Gems',
    album: 'Sparkle',
    duration: 247,
    imageUrl: 'https://picsum.photos/300/300?random=27',
  },
  {
    id: 'song-28',
    title: 'Phoenix Rising',
    artist: 'Rebirth Band',
    album: 'New Beginnings',
    duration: 271,
    imageUrl: 'https://picsum.photos/300/300?random=28',
  },
  {
    id: 'song-29',
    title: 'Silent Night',
    artist: 'Quiet Moments',
    album: 'Peaceful',
    duration: 188,
    imageUrl: 'https://picsum.photos/300/300?random=29',
  },
  {
    id: 'song-30',
    title: 'Cosmic Dance',
    artist: 'Space Walkers',
    album: 'Zero Gravity',
    duration: 264,
    imageUrl: 'https://picsum.photos/300/300?random=30',
  },
  {
    id: 'song-31',
    title: 'Waterfall Rush',
    artist: 'River Flow',
    album: 'Liquid Motion',
    duration: 229,
    imageUrl: 'https://picsum.photos/300/300?random=31',
  },
  {
    id: 'song-32',
    title: 'Fire and Ice',
    artist: 'Temperature Rising',
    album: 'Extremes',
    duration: 252,
    imageUrl: 'https://picsum.photos/300/300?random=32',
  },
  {
    id: 'song-33',
    title: 'Gravity Well',
    artist: 'Heavy Bass',
    album: 'Deep Space',
    duration: 276,
    imageUrl: 'https://picsum.photos/300/300?random=33',
  },
  {
    id: 'song-34',
    title: 'Wind Chimes',
    artist: 'Breeze Makers',
    album: 'Air',
    duration: 197,
    imageUrl: 'https://picsum.photos/300/300?random=34',
  },
  {
    id: 'song-35',
    title: 'Shadow Play',
    artist: 'Dark Ambient',
    album: 'Shadows',
    duration: 238,
    imageUrl: 'https://picsum.photos/300/300?random=35',
  },
  {
    id: 'song-36',
    title: 'Sunburst',
    artist: 'Solar Flare',
    album: 'Brightness',
    duration: 220,
    imageUrl: 'https://picsum.photos/300/300?random=36',
  },
  {
    id: 'song-37',
    title: 'Mystic Portal',
    artist: 'Enigma Machine',
    album: 'Hidden Worlds',
    duration: 283,
    imageUrl: 'https://picsum.photos/300/300?random=37',
  },
  {
    id: 'song-38',
    title: 'Orbital Motion',
    artist: 'Planet Groove',
    album: 'Planetary',
    duration: 255,
    imageUrl: 'https://picsum.photos/300/300?random=38',
  },
  {
    id: 'song-39',
    title: 'Aurora Wake',
    artist: 'Dawn Chorus',
    album: 'Morning Light',
    duration: 211,
    imageUrl: 'https://picsum.photos/300/300?random=39',
  },
  {
    id: 'song-40',
    title: 'Infinite Loop',
    artist: 'Code Runner',
    album: 'Software',
    duration: 243,
    imageUrl: 'https://picsum.photos/300/300?random=40',
  },
  {
    id: 'song-41',
    title: 'Velvet Blue',
    artist: 'Deep Color',
    album: 'Hues',
    duration: 265,
    imageUrl: 'https://picsum.photos/300/300?random=41',
  },
  {
    id: 'song-42',
    title: 'Sonic Boom',
    artist: 'Thunderous Sound',
    album: 'Explosions',
    duration: 208,
    imageUrl: 'https://picsum.photos/300/300?random=42',
  },
  {
    id: 'song-43',
    title: 'Twilight Zone',
    artist: 'Between Times',
    album: 'Liminal',
    duration: 237,
    imageUrl: 'https://picsum.photos/300/300?random=43',
  },
  {
    id: 'song-44',
    title: 'Cascade Falls',
    artist: 'Water Bearer',
    album: 'Flow',
    duration: 270,
    imageUrl: 'https://picsum.photos/300/300?random=44',
  },
  {
    id: 'song-45',
    title: 'Prism Light',
    artist: 'Spectrum',
    album: 'Rainbow',
    duration: 221,
    imageUrl: 'https://picsum.photos/300/300?random=45',
  },
  {
    id: 'song-46',
    title: 'Frost Bite',
    artist: 'Ice Breakers',
    album: 'Cold',
    duration: 246,
    imageUrl: 'https://picsum.photos/300/300?random=46',
  },
  {
    id: 'song-47',
    title: 'Thunder Drums',
    artist: 'Percussion Kings',
    album: 'Rhythm Nation',
    duration: 234,
    imageUrl: 'https://picsum.photos/300/300?random=47',
  },
  {
    id: 'song-48',
    title: 'Moonlight Serenade',
    artist: 'Night Owl',
    album: 'Nocturnal',
    duration: 259,
    imageUrl: 'https://picsum.photos/300/300?random=48',
  },
  {
    id: 'song-49',
    title: 'Eternal Flame',
    artist: 'Forever Burning',
    album: 'Immortal',
    duration: 272,
    imageUrl: 'https://picsum.photos/300/300?random=49',
  },
  {
    id: 'song-50',
    title: 'Void Echo',
    artist: 'Silent Void',
    album: 'Empty Space',
    duration: 199,
    imageUrl: 'https://picsum.photos/300/300?random=50',
  },
  {
    id: 'song-51',
    title: 'Harmony Line',
    artist: 'Perfect Chord',
    album: 'Melodic',
    duration: 228,
    imageUrl: 'https://picsum.photos/300/300?random=51',
  },
  {
    id: 'song-52',
    title: 'Velocity Rise',
    artist: 'Speed Demon',
    album: 'Fast Track',
    duration: 181,
    imageUrl: 'https://picsum.photos/300/300?random=52',
  },
  {
    id: 'song-53',
    title: 'Twilight Breeze',
    artist: 'Evening Wind',
    album: 'Sunset Sessions',
    duration: 245,
    imageUrl: 'https://picsum.photos/300/300?random=53',
  },
  {
    id: 'song-54',
    title: 'Neon Nights',
    artist: 'City Lights Collective',
    album: 'Urban Glow',
    duration: 256,
    imageUrl: 'https://picsum.photos/300/300?random=54',
  },
  {
    id: 'song-55',
    title: 'Ocean Deep',
    artist: 'Aquatic Souls',
    album: 'Blue Horizons',
    duration: 272,
    imageUrl: 'https://picsum.photos/300/300?random=55',
  },
  {
    id: 'song-56',
    title: 'Mountain Echo',
    artist: 'Peak Sounds',
    album: 'Alpine Calls',
    duration: 239,
    imageUrl: 'https://picsum.photos/300/300?random=56',
  },
  {
    id: 'song-57',
    title: 'Desert Mirage',
    artist: 'Sand Dunes',
    album: 'Oasis',
    duration: 213,
    imageUrl: 'https://picsum.photos/300/300?random=57',
  },
  {
    id: 'song-58',
    title: 'Forest Dreams',
    artist: 'Woodland Echo',
    album: 'Green Dreams',
    duration: 248,
    imageUrl: 'https://picsum.photos/300/300?random=58',
  },
  {
    id: 'song-59',
    title: 'Sky High',
    artist: 'Cloud Nine',
    album: 'Above the Clouds',
    duration: 224,
    imageUrl: 'https://picsum.photos/300/300?random=59',
  },
  {
    id: 'song-60',
    title: 'Starlight',
    artist: 'Celestial Bodies',
    album: 'Night Sky',
    duration: 260,
    imageUrl: 'https://picsum.photos/300/300?random=60',
  },
  {
    id: 'song-61',
    title: 'Rain Dance',
    artist: 'Water Rhythms',
    album: 'Precipitation',
    duration: 227,
    imageUrl: 'https://picsum.photos/300/300?random=61',
  },
  {
    id: 'song-62',
    title: 'Wind Whisper',
    artist: 'Air Currents',
    album: 'Gentle Breeze',
    duration: 195,
    imageUrl: 'https://picsum.photos/300/300?random=62',
  },
  {
    id: 'song-63',
    title: 'Stone Melody',
    artist: 'Rock Echoes',
    album: 'Granite Harmonies',
    duration: 243,
    imageUrl: 'https://picsum.photos/300/300?random=63',
  },
  {
    id: 'song-64',
    title: 'Thunder Storm',
    artist: 'Electric Nature',
    album: 'Power Surge',
    duration: 254,
    imageUrl: 'https://picsum.photos/300/300?random=64',
  },
  {
    id: 'song-65',
    title: 'Soft Whisper',
    artist: 'Quiet Voices',
    album: 'Intimate Moments',
    duration: 189,
    imageUrl: 'https://picsum.photos/300/300?random=65',
  },
  {
    id: 'song-66',
    title: 'Jazz Nights',
    artist: 'Blue Notes',
    album: 'Late Night Sessions',
    duration: 262,
    imageUrl: 'https://picsum.photos/300/300?random=66',
  },
  {
    id: 'song-67',
    title: 'Pop Culture',
    artist: 'Chart Toppers',
    album: 'Hits Collection',
    duration: 204,
    imageUrl: 'https://picsum.photos/300/300?random=67',
  },
  {
    id: 'song-68',
    title: 'Rock Anthem',
    artist: 'Stone Hearts',
    album: 'Power Chords',
    duration: 268,
    imageUrl: 'https://picsum.photos/300/300?random=68',
  },
  {
    id: 'song-69',
    title: 'Soul Music',
    artist: 'Deep Feeling',
    album: 'Emotional Journey',
    duration: 247,
    imageUrl: 'https://picsum.photos/300/300?random=69',
  },
  {
    id: 'song-70',
    title: 'Classical Grace',
    artist: 'Orchestral Dreams',
    album: 'Symphony No. 1',
    duration: 285,
    imageUrl: 'https://picsum.photos/300/300?random=70',
  },
  {
    id: 'song-71',
    title: 'Electronic Beat',
    artist: 'Digital Groove',
    album: 'Synth Wave',
    duration: 219,
    imageUrl: 'https://picsum.photos/300/300?random=71',
  },
  {
    id: 'song-72',
    title: 'Country Roads',
    artist: 'Rural Strings',
    album: 'Down Home',
    duration: 231,
    imageUrl: 'https://picsum.photos/300/300?random=72',
  },
  {
    id: 'song-73',
    title: 'reggae Vibes',
    artist: 'Island Rhythm',
    album: 'Tropical Beats',
    duration: 250,
    imageUrl: 'https://picsum.photos/300/300?random=73',
  },
  {
    id: 'song-74',
    title: 'Hip Hop Flow',
    artist: 'Urban Poets',
    album: 'Street Stories',
    duration: 216,
    imageUrl: 'https://picsum.photos/300/300?random=74',
  },
  {
    id: 'song-75',
    title: 'Indie Spirit',
    artist: 'Underground Kings',
    album: 'Alternative Vibes',
    duration: 244,
    imageUrl: 'https://picsum.photos/300/300?random=75',
  },
  {
    id: 'song-76',
    title: 'Folk Tales',
    artist: 'Traditional Roots',
    album: 'Ancient Stories',
    duration: 258,
    imageUrl: 'https://picsum.photos/300/300?random=76',
  },
  {
    id: 'song-77',
    title: 'Latin Fire',
    artist: 'Salsa Kings',
    album: 'Tropical Heat',
    duration: 263,
    imageUrl: 'https://picsum.photos/300/300?random=77',
  },
  {
    id: 'song-78',
    title: 'Metal Fury',
    artist: 'Heavy Distortion',
    album: 'Amplified Chaos',
    duration: 277,
    imageUrl: 'https://picsum.photos/300/300?random=78',
  },
  {
    id: 'song-79',
    title: 'Blues Cry',
    artist: 'Soulful Moans',
    album: 'Midnight Sadness',
    duration: 269,
    imageUrl: 'https://picsum.photos/300/300?random=79',
  },
  {
    id: 'song-80',
    title: 'Gospel Light',
    artist: 'Heavenly Choir',
    album: 'Spiritual Ascent',
    duration: 291,
    imageUrl: 'https://picsum.photos/300/300?random=80',
  },
  {
    id: 'song-81',
    title: 'Ambient Space',
    artist: 'Cosmic Soundscapes',
    album: 'Ethereal Waves',
    duration: 301,
    imageUrl: 'https://picsum.photos/300/300?random=81',
  },
  {
    id: 'song-82',
    title: 'Dance Fever',
    artist: 'Club Vibes',
    album: 'Night Out',
    duration: 230,
    imageUrl: 'https://picsum.photos/300/300?random=82',
  },
  {
    id: 'song-83',
    title: 'Funk Machine',
    artist: 'Groove Masters',
    album: 'Get Down',
    duration: 240,
    imageUrl: 'https://picsum.photos/300/300?random=83',
  },
  {
    id: 'song-84',
    title: 'Disco Nights',
    artist: 'Shining Stars',
    album: 'Glitter Ball',
    duration: 255,
    imageUrl: 'https://picsum.photos/300/300?random=84',
  },
  {
    id: 'song-85',
    title: 'K-Pop Dream',
    artist: 'Seoul Voices',
    album: 'Asiatic Beats',
    duration: 225,
    imageUrl: 'https://picsum.photos/300/300?random=85',
  },
  {
    id: 'song-86',
    title: 'Mandarin Flow',
    artist: 'Shanghai Sounds',
    album: 'East Harmony',
    duration: 248,
    imageUrl: 'https://picsum.photos/300/300?random=86',
  },
  {
    id: 'song-87',
    title: 'Bollywood Magic',
    artist: 'Mumbai Hearts',
    album: 'Spice Dreams',
    duration: 274,
    imageUrl: 'https://picsum.photos/300/300?random=87',
  },
  {
    id: 'song-88',
    title: 'Afro Beat',
    artist: 'Lagos Rhythm',
    album: 'African Pride',
    duration: 266,
    imageUrl: 'https://picsum.photos/300/300?random=88',
  },
  {
    id: 'song-89',
    title: 'Celtic Whistle',
    artist: 'Irish Legends',
    album: 'Emerald Isle',
    duration: 237,
    imageUrl: 'https://picsum.photos/300/300?random=89',
  },
  {
    id: 'song-90',
    title: 'Flamenco Passion',
    artist: 'Spanish Fire',
    album: 'Gypsy Soul',
    duration: 253,
    imageUrl: 'https://picsum.photos/300/300?random=90',
  },
  {
    id: 'song-91',
    title: 'Techno Pulse',
    artist: 'Berlin Underground',
    album: 'Industrial Age',
    duration: 296,
    imageUrl: 'https://picsum.photos/300/300?random=91',
  },
  {
    id: 'song-92',
    title: 'House Vibes',
    artist: 'Chicago Deep',
    album: 'Underground Sounds',
    duration: 282,
    imageUrl: 'https://picsum.photos/300/300?random=92',
  },
  {
    id: 'song-93',
    title: 'Trance State',
    artist: 'Ibiza Dreams',
    album: 'Summer Paradise',
    duration: 298,
    imageUrl: 'https://picsum.photos/300/300?random=93',
  },
  {
    id: 'song-94',
    title: 'Dubstep Drop',
    artist: 'Bass Hunters',
    album: 'Heavy Drops',
    duration: 267,
    imageUrl: 'https://picsum.photos/300/300?random=94',
  },
  {
    id: 'song-95',
    title: 'Garage Rock',
    artist: 'Basement Amps',
    album: 'Noise Makers',
    duration: 234,
    imageUrl: 'https://picsum.photos/300/300?random=95',
  },
  {
    id: 'song-96',
    title: 'Punk Rebellion',
    artist: 'Rotten Strings',
    album: 'Anarchy Sound',
    duration: 187,
    imageUrl: 'https://picsum.photos/300/300?random=96',
  },
  {
    id: 'song-97',
    title: 'Grunge Anthem',
    artist: 'Seattle Legends',
    album: 'Sad Tomorrow',
    duration: 279,
    imageUrl: 'https://picsum.photos/300/300?random=97',
  },
  {
    id: 'song-98',
    title: 'Psychedelic Trip',
    artist: 'Trippy Minds',
    album: 'Alternate Reality',
    duration: 310,
    imageUrl: 'https://picsum.photos/300/300?random=98',
  },
  {
    id: 'song-99',
    title: 'Minimalist Bell',
    artist: 'Simple Tones',
    album: 'Less is More',
    duration: 175,
    imageUrl: 'https://picsum.photos/300/300?random=99',
  },
  {
    id: 'song-100',
    title: 'Epic Symphony',
    artist: 'Grand Orchestras',
    album: 'Timeless Masterpiece',
    duration: 315,
    imageUrl: 'https://picsum.photos/300/300?random=100',
  },
  {
    id: 'song-101',
    title: 'Retro Synth',
    artist: 'Vintage Machines',
    album: '80s Nostalgia',
    duration: 241,
    imageUrl: 'https://picsum.photos/300/300?random=101',
  },
  {
    id: 'song-102',
    title: 'Future Sound',
    artist: 'AI Composers',
    album: 'Next Generation',
    duration: 258,
    imageUrl: 'https://picsum.photos/300/300?random=102',
  },
];

export async function GET(request: NextRequest) {
  const searchParams = request.nextUrl.searchParams;
  const query = searchParams.get('q');

  if (!query) {
    return NextResponse.json(MOCK_SONGS);
  }

  const lowerQuery = query.toLowerCase();
  const filtered = MOCK_SONGS.filter(
    (song) =>
      song.title.toLowerCase().includes(lowerQuery) ||
      song.artist.toLowerCase().includes(lowerQuery) ||
      song.album.toLowerCase().includes(lowerQuery)
  );

  return NextResponse.json(filtered);
}
